// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe2gQ-PkVXSvumNxaE6BLFazCX1pq_t5s',
    appId: '1:443738163889:web:1af770b1b10f0a6fd2f090',
    messagingSenderId: '443738163889',
    projectId: 'sample-project-2dc3a',
    authDomain: 'sample-project-2dc3a.firebaseapp.com',
    storageBucket: 'sample-project-2dc3a.firebasestorage.app',
    measurementId: 'G-1KB1VEBHBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFN9Q4ObF3mxVU7-T0FhZzRqslXey6pWI',
    appId: '1:443738163889:android:83f818a3245aa162d2f090',
    messagingSenderId: '443738163889',
    projectId: 'sample-project-2dc3a',
    storageBucket: 'sample-project-2dc3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD48VUP5a87XbFCwXGAp7AUxX1Ns0yu38s',
    appId: '1:443738163889:ios:62cfd3d192dfab4bd2f090',
    messagingSenderId: '443738163889',
    projectId: 'sample-project-2dc3a',
    storageBucket: 'sample-project-2dc3a.firebasestorage.app',
    iosBundleId: 'com.example.authScreen',
  );
}
